export const PLACES:[string,number,number][]=[['Shibuya',35.6595,139.7005],['Shinjuku',35.6905,139.7001],['Tokyo Station',35.6813,139.7653],['Asakusa',35.711,139.7964],['Ginza',35.6717,139.7649],['Odaiba',35.6298,139.7756],['Kichijoji',35.702,139.5797],['Tachikawa',35.6991,139.412],['Hachioji',35.6564,139.3383],['Ome',35.7905,139.2603],['Okutama',35.8091,139.0977],['Oshima',34.7501,139.3553],['Hachijo',33.1111,139.7905],['Chichijima',27.0947,142.1918]];
const px=(lat:number,lon:number,z:number)=>{const s=256*2**z;return{x:(lon+180)/360*s,y:(1-Math.asinh(Math.tan(lat*Math.PI/180))/Math.PI)/2*s};};
const ll=(x:number,y:number,z:number)=>{const s=256*2**z;return{lon:x/s*360-180,lat:Math.atan(Math.sinh(Math.PI*(1-2*y/s)))*180/Math.PI};};
export function setupMap(travel:(lat:number,lon:number,name:string)=>void,current:()=>{lat:number,lon:number}){
 const dialog=document.querySelector<HTMLDialogElement>('#map-dialog')!,canvas=document.querySelector<HTMLDivElement>('#map-canvas')!,tiles=document.querySelector<HTMLDivElement>('#map-tiles')!;let center={lat:35.7,lon:139.55},zoom=11,drag:{x:number,y:number,cx:number,cy:number,moved:boolean}|null=null;
 function draw(){const c=px(center.lat,center.lon,zoom),w=canvas.clientWidth,h=canvas.clientHeight,left=c.x-w/2,top=c.y-h/2;tiles.replaceChildren();for(let x=Math.floor(left/256);x<=Math.floor((left+w)/256);x++)for(let y=Math.floor(top/256);y<=Math.floor((top+h)/256);y++){const im=document.createElement('img');im.src=`https://cyberjapandata.gsi.go.jp/xyz/std/${zoom}/${x}/${y}.png`;im.style.left=`${x*256-left}px`;im.style.top=`${y*256-top}px`;im.alt='';tiles.append(im);}const p=current(),point=px(p.lat,p.lon,zoom),marker=document.createElement('div');marker.style.cssText=`position:absolute;left:${point.x-left-6}px;top:${point.y-top-6}px;width:12px;height:12px;border:2px solid white;border-radius:50%;background:#244c39;box-shadow:0 0 0 5px #244c3940`;tiles.append(marker);}
 function go(lat:number,lon:number,name:string){dialog.close();travel(lat,lon,name);}
 const open=()=>{document.exitPointerLock();center=current();zoom=11;dialog.showModal();draw();};document.querySelector('#map-button')!.addEventListener('click',open);document.querySelector('#close-map')!.addEventListener('click',()=>dialog.close());
 for(const [name,lat,lon]of PLACES){const b=document.createElement('button');b.textContent=name;b.onclick=()=>go(lat,lon,name);document.querySelector('#places')!.append(b);}
 document.querySelector('#coordinate-form')!.addEventListener('submit',e=>{e.preventDefault();const lat=Number((document.querySelector('#lat')as HTMLInputElement).value),lon=Number((document.querySelector('#lon')as HTMLInputElement).value);if(lat>=20&&lat<=36.1&&lon>=136&&lon<=154)go(lat,lon,'Custom coordinates');else alert('Enter coordinates within the Tokyo mainland / island region.');});
 canvas.onpointerdown=e=>{if((e.target as HTMLElement).closest('button'))return;const c=px(center.lat,center.lon,zoom);drag={x:e.clientX,y:e.clientY,cx:c.x,cy:c.y,moved:false};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>5)drag.moved=true;center=ll(drag.cx-dx,drag.cy-dy,zoom);draw();};canvas.onpointerup=e=>{if(!drag)return;if(!drag.moved){const r=canvas.getBoundingClientRect(),c=px(center.lat,center.lon,zoom),p=ll(c.x+e.clientX-r.left-r.width/2,c.y+e.clientY-r.top-r.height/2,zoom);go(p.lat,p.lon,'Map destination');}drag=null;};
 const zoomBy=(d:number)=>{zoom=Math.max(5,Math.min(18,zoom+d));draw();};document.querySelector('#zoom-in')!.addEventListener('click',()=>zoomBy(1));document.querySelector('#zoom-out')!.addEventListener('click',()=>zoomBy(-1));canvas.addEventListener('wheel',e=>{e.preventDefault();zoomBy(e.deltaY<0?1:-1);},{passive:false});return{open};
}
